name: CI

on: push

jobs:
  check:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ 17 ]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java }}

      - name: Setup Gradle cache
        uses: actions/cache@v2
        with:
          path: ~/.gradle
          key: ${{ runner.os }}-${{ matrix.java }}-gradle-${{ hashFiles('build.gradle') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.java }}-gradle

      - name: Check
        run: ./gradlew check

      - name: Upload Gradle reports
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: Gradle Reports ${{ matrix.java }}
          path: "**/build/reports"
