name: CI

on: push

jobs:
  check:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ 8, 16 ]

    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1

      - name: Setup JDK
        uses: actions/setup-java@v1.4.3
        with:
          java-version: ${{ matrix.java }}

      - name: Setup Gradle cache
        uses: actions/cache@v2.1.0
        with:
          path: ~/.gradle
          key: ${{ runner.os }}-${{ matrix.java }}-gradle-${{ hashFiles('build.gradle') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.java }}-gradle

      - name: Check
        run: ./gradlew check
