name: Dependency Submission

on:
  push:
    branches: [ 'main' ]

jobs:
  dependency-submission:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup JDK
        uses: actions/setup-java@v5
        with:
          java-version: 17
          distribution: temurin

      - name: Generate and submit dependency graph
        uses: gradle/actions/dependency-submission@v5
